name: Playwright Tests
on: workflow_dispatch
jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-24.04
    container:
      image: mcr.microsoft.com/playwright/python:v1.49.1-noble
      options: --user 1001
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Add local bin to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Run your tests
        run: pytest --alluredir=allure-results || true
        continue-on-error: true

      - uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
          retention-days: 20

      - name: Get Allure history
        uses: actions/checkout@v4.1.1
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@v1.9
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.TEST_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
